const Tokens = {
    Select: 1,
    Create: 2,
    Insert: 3,
    Update: 4,
    Delete: 5,
    Where: 6,
    Using: 7,
    On: 8,
    Open_Par: 9,
    Close_Par: 10,
    Open_Brace: 11,
    Close_Brace: 12,
    Identifier: 13,
    Int_Literal: 14,
    Float_Literal: 15,
    String_Literal: 16,
    Bool_Literal: 17,
    Date_Literal: 18,
    Spread_Operator: 19,
    Dot_Operator: 20,
    Assign_Operator: 21,
    Logical_Not_Operator: 22,
    Logical_Or_Operator: 23,
    Logical_And_Operator: 24,
    Logical_GreaterThan_Operator: 25,
    Logical_LessThan_Operator: 26,
    Logical_Equal_Operator: 27,
    Logical_NotEqual_Operator: 28,
    Logical_GreaterEqual_Operator: 29,
    Logical_LessEqual_Operator: 30,
    ERROR: 31,  
};


export default Tokens;